### ISSUE TITLE
Propriedades do lg deixou de funcionar na version 1.4.63

### ISSUE THREAD

**Issue by martinezpoa** [xproglabs/prensa-designsystem#105]
Ao atualizar para a versão 1.4.63 a props lg do `Block` deixou de funcionar.

Impacto no projeto: Diário da Região

<img width="1440" alt="Captura de Tela 2021-02-08 às 17 19 55" src="https://user-images.githubusercontent.com/19194161/107276812-557b8700-6a32-11eb-96c3-31c0e49a8093.png">

**Comment by gbombassaro** [comment]
Corrigido na versão 1.4.64
