### ISSUE TITLE
O fontFamily não está aplicando a regra quando inserido no button

### ISSUE THREAD

**Issue by martinezpoa** [xproglabs/prensa-designsystem#106]
<img width="1110" alt="Captura de Tela 2021-02-13 às 11 42 05" src="https://user-images.githubusercontent.com/19194161/107852655-ccc56800-6df0-11eb-8853-3c058903d486.png">

<img width="468" alt="Captura de Tela 2021-02-13 às 11 45 21" src="https://user-images.githubusercontent.com/19194161/107852702-0302e780-6df1-11eb-877f-58ffb4ac791c.png">

**Comment by gbombassaro** [comment]
@martinezpoa testei localmente e está funcionando corretamente a troca da fonte. Pode mandar um print do teu theme? Derrepente está faltando propriedades lá dentro. Temos que ter:
<pre>fonts: {primary: "", secondary: ""}</pre>

Caso contrário o Button não vai achar o valor correspondente. Atualiza também a tua versão do Prensa, subi agora um ajuste que troca a defaultProps de `fontFamily` para secondary.
