### ISSUE TITLE
CSS final gerado pela build é maior do que o permitido pelo AMP

### ISSUE THREAD

**Issue by bombassaro** [xproglabs/prensa-designsystem#109]
### Contexto

- O CSS final gerado pela build da aplicação ficou com tamanho maior do que o máximo permitido pelo AMP (75000 bytes). Identifiquei que mais de metade do tamanho do CSS gerado é derivado das variáveis de alinhamento do Block.

### O que fazer

- Unificar as classes aplicadas para alinhamento para que não haja a repetição das regras comuns
- Unificar a aplicação das propriedades para os media queries responsivos (principalmente o lg)

### Critérios de aceitação

- O CSS após a build deve ficar com menos de 75000 bytes.

### Anexos / Evidências

![Screen Shot 2021-02-27 at 12 15 55](https://user-images.githubusercontent.com/1500027/109391396-a0801000-78f5-11eb-814c-afc7cfeb2e9b.png)

**Comment by gbombassaro** [comment]
Resolvido removendo os vendors-prefix do css.
