### ISSUE TITLE
Implementar customClass e customId no Block

### ISSUE THREAD

**Issue by bombassaro** [xproglabs/prensa-designsystem#117]
Contexto
- O componente Block não permite adicionar classe customizada nem id referenciador
- Sem a classe customizada seria necessário adicionar mais uma div só para marcação
- A classe customizada permitirá automatizar a cor de blocos de notícias por editoria
- A classe customizada permitirá reduzir a utilização da propriedade custom

O que fazer
- Adicionar propriedade customClass na propriedade className da div do Block
- Adicionar propriedade customId na propriedade id da div do Block

**Comment by gbombassaro** [comment]
Por que não usamos o nome da prop normal `class` e `id`? Podemos usar `className` no contexto do react também
