### ISSUE TITLE
Propriedade onChange do Field component deixou de funcionar

### ISSUE THREAD

**Issue by bombassaro** [xproglabs/prensa-designsystem#128]
Comportamento aparece na versão: 1.4.82
Na versão 1.4.77 está funcionando

Como está sendo declarado:
```
onChange={set_email}
value={field_email}
```

Resultado: o valor do field nunca modifica

**Comment by gbombassaro** [comment]
@bombassaro foi corrigido no PR #129 . Só atualizar o prensa no front `npm install prensa@latest`
