### ISSUE TITLE
Falha de versionamento na build local

### ISSUE THREAD

**Issue by martinezpoa** [xproglabs/prensa-designsystem#441]
Tentamos fazer a build local (yarn release:local) usando as versões do node 15.11.0 e 16 porém ambas falham. A primeira é impedida por uma incompatibilidade do semantic release com o node 15. E a segunda, da falha no import do theme (withStyles).

Como simular: Fazer a build local usando o node 15.11 ou node 16

**Comment by matheusPinheiroP** [comment]
https://semantic-release.gitbook.io/semantic-release/support/node-version

**Comment by matheusPinheiroP** [comment]
Estranho. Estou usando a versão LTS do Node e esse problema não apareceu, como esse problema aconteceu em 2 máquinas MacOS, poderíamos ver se mais alguém vai ter esse problema. No Ubuntu está normal

**Comment by gbombassaro** [comment]
@martinezpoa @bombassaro testei na minha máquina local usando a versão LTS 16.13.1. Podem compartilhar um trace do erro? E também atualizar as versões do Node de vcs para a LTS

**Comment by bombassaro** [comment]
Resolvido após atuailzarmos para a versão LTS do Node
